project:
  type: website
  output-dir: docs

website:
  title: "Ismaël Lajaaiti"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ilajaait
      - icon: twitter
        href: https://twitter.com/ismael_lajaaiti
format:
  html:
    theme: litera
    css: styles.css



